### ISSUE TITLE
Show limit defaults next to adapter capabilities

### ISSUE THREAD

**Issue by kainino0x** [webgpu/webgpureport.org#17]
e.g. by creating a default device from the adapter and showing what its capabilities are.

This would be [helpful](https://matrix.to/#/!MFogdGJfnZLrDmgkBN:matrix.org/$ot_Fftp7RNV1U6uo2kuPoND5TIBKZzyp4iZZ3xnOS_Q?via=matrix.org&via=mozilla.org&via=matrix.nrp-nautilus.io) to people before they have learned about WebGPU's system where it enforces the minimum limits by default.

Also in compat, it will show different values even on systems that have core and allow all of the core limits on compat adapters.

**Comment by greggman** [comment]
I'm happy to add something, I just didn't want things to get cluttered since 3 adapters fit on my MBP right now (which show up when compat and fallback are enabled)

As it is that info is available by hovering (yea, that's not very discoverable)

<img width="523" alt="Screenshot 2024-07-22 at 15 49 49" src="https://github.com/user-attachments/assets/c2e55228-2b57-4eb5-aa0b-e5a205b4020f">

If the limit is > core default the value shows up in orange. If the limit is < core then it's in red (this is for compat)

**Comment by greggman** [comment]
Oh, and good idea to create the device to find the defaults. Right now they're hard coded with a 3rd color for when they're missing.
